### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by stephannielsen**
I updated the projects to VS2019 with new .csproj file format (PackageReference instead of packages.config) and .netstandard library for the shared project instead of PCL. Also updated the dependencies and adjusted the code for the new APIs.

So far I've only tested Android - app works as expected but I haven't checked everything. iOS builds but is not tested yet, but I plan to.

Would you be interested in such a PR?

### CODE REVIEW

**Comment by SmartyP** [comment]
Hey Stephan, thanks for working on this. My apologies for the very slow response, I've been out of town most of the last few months. 

I would definitely be interested in such a PR. I gave it a whirl on iOS, and it looks like there are new icon requirements that prevent iOS from building. I've created a new set of icons, which when dropped in `LineDietXF/iOS/Assets.xcassets/AppIcon.appiconset` seem to fix the build issue - you can find a zip of those icons here:
https://www.dropbox.com/s/ml2g8eiarjwmsm7/NewiOSIcons.zip?dl=0

After that fix, I ran into a new runtime crash on line 46 in `CustomTabbedPageRenderer.cs`. That can be fixed by changing:
`var iconFilename = tabPage.IconImageSource + UnselectedFilenameExtension;`
to:
`var iconFilename = ((FileImageSource)tabPage.IconImageSource).FIle + UnselectedFilenameExtension;`

After fixing that runtime crash the other issue I noticed on iOS is that the tabs are now blue when selected instead of white. It looks like there may have been some breaking changes there and that `CustomTabbedPageRenderer.OnElementChanged()` may need to be revisited to address. 

If you decide to keep working on this PR I would definitely be interested in it. I am at least setup again to compile/run this project (new Mac, so had to setup before reviewing this).

Thanks again!

**Comment by stephannielsen** [comment]
Awesome, thank you! 

I did not work on this any further, so I guess I can update the dependencies again 😄  and include your suggestions and check out the iOS issue.

But I did use the updated version of the app and noticed significant performance increase already in startup time - which is mostly the reason why I started with this in the first place 😄 

I will let you know once I have more to show.

**Comment by stephannielsen** [comment]
Updated the dependencies once more and applied the iOS changes. Will see to get my mac up and running with this to check out the styling issue too.

**Comment by stephannielsen** [comment]
I fixed the iOS issues with the tabbar and also fixed wrong color of the status bar (always switched to black once app was started).

Any other issues on iOS that changed because of the upgrades?

**Comment by stephannielsen** [comment]
Missed to add the commit with the iOS fixes. All there now.

**Comment by SmartyP** [comment]
Sorry for the delay on this, thanks again for taking the time to do it.

**Pull request merged**
